### ISSUE TITLE
建议dl.google.com/go/换了

### ISSUE THREAD

**Issue by Potterli20** [Jrohy/go-install#2]
建议dl.google.com/go/换了，换成golang.google.cn/dl的地址

**Comment by Jrohy** [comment]
测试了下里面的文件下载地址还是调用官网的地址https://dl.google.com/go/go1.16.linux-amd64.tar.gz, 而且测试这个下载地址貌似没墙可以下载的

**Comment by Jrohy** [comment]
你在你的linux试试 wget https://dl.google.com/go/go1.16.linux-amd64.tar.gz能否下载， 我用腾讯云的vps测试下载挺快的速度

**Comment by Jrohy** [comment]
dl.google.com虽然被墙了，但https://dl.google.com/go/go1.16.linux-amd64.tar.gz能下载，感觉就是豁免了

**Comment by Jrohy** [comment]
脚本已换成gomirrors.org国内镜像源来下载了，可以再试试
