### ISSUE TITLE
哈哈哈，又有问题了

### ISSUE THREAD

**Issue by Potterli20** [Jrohy/go-install#5]
![2021-12-06 09-32-35 的屏幕截图](https://user-images.githubusercontent.com/28734349/144774122-e1240190-5cbd-4cac-908c-5eebe0a26a61.png)

**Comment by Jrohy** [comment]
再试试，我这边能打开

**Comment by Potterli20** [comment]
> 再试试，我这边能打开

因为我是用国内的，我那边是520的

**Comment by Jrohy** [comment]
确实不行，看过一阵子能否恢复

**Comment by Potterli20** [comment]
> 确实不行，看过一阵子能否恢复

那就可以写个选项
如1:github
2:官方
3:镜像
但好像工程有点小大

**Comment by Jrohy** [comment]
不会这么弄，还要人为选就太笨了，过几天还不行就找找替代方案

**Comment by Potterli20** [comment]
镜像
https://studygolang.com/dl
https://golang.google.cn/
https://golang.google.cn/dl
![2021-12-06 09-32-35 的屏幕截图](https://user-images.githubusercontent.com/28734349/144776315-315e3001-d0ca-468f-b781-7e32d38f6f54.png)
/

**Comment by Jrohy** [comment]
已变更检查地址

**Comment by Potterli20** [comment]
> 已变更检查地址

己正常更新

**Comment by Potterli20** [comment]
proxy.golang.or
![2021-12-06 10-12-07 的屏幕截图](https://user-images.githubusercontent.com/28734349/144777593-8f523b4d-093f-48ab-a3f8-bc86d41d89b0.png)
g

**Comment by Potterli20** [comment]
gfw又来了

**Comment by Potterli20** [comment]
镜像proxy golang
https://goproxy.cn/
https://goproxy.io/

**Comment by Jrohy** [comment]
脚本检测到国内网络环境会自动设置goproxy.cn代理的

**Comment by Potterli20** [comment]
> 脚本检测到国内网络环境会自动设置goproxy.cn代理的

可能是我代理环境问题😂
