### ISSUE TITLE
如何配置交叉编译工具之类？

### ISSUE THREAD

**Issue by Potterli20** [Jrohy/go-install#6]
就是这种的
![Screenshot_2022-03-13-14-26-57-367_com.chrome.dev.jpg](https://user-images.githubusercontent.com/28734349/158047934-6d7d87ee-9720-4342-82b4-f6d25a2116af.jpg)

**Comment by Potterli20** [comment]
就是有没有小白那种一建配置？

**Comment by Jrohy** [comment]
没有，xgo都不更新了，自己敲命令就行了交叉编译go很简单的

**Comment by Jrohy** [comment]
此仓库只是安装go，没其他的功能

**Comment by Potterli20** [comment]
> 此仓库只是安装go，没其他的功能

好的好的
