### ISSUE TITLE
Non-root user is not considered?

### ISSUE THREAD

**Issue by pluveto** [Jrohy/go-install#9]
source <(curl -L https://go-install.netlify.app/install.sh)

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6099  100  6099    0     0  20744      0 --:--:-- --:--:-- --:--:-- 20744
正在获取最新版golang...
最新版golang: 1.20.5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95.5M  100 95.5M    0     0  5782k      0  0:00:16  0:00:16 --:--:-- 5646k
install_updater:3: permission denied: /usr/local/bin/goupdate
chmod: cannot access '/usr/local/bin/goupdate': No such file or directory

**Comment by Jrohy** [comment]
不支持非root用户
